# Generated by Django 4.2.7 on 2023-11-21 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drones',
            name='battery',
            field=models.CharField(default='Not Connected', max_length=12),
        ),
    ]
